# The Python Primer

This is a collection of various Python primers. The purpose is to have a comprehensive practice / reference guide which helps the reader build their familarity with the python language. Remember the more you practice the better you get. Following references were used. 


1. Hands on Python for Finance at Alaxender Street : Video Link is : https://video-alexanderstreet-com.proxy.library.nyu.edu/watch/hands-on-python-for-finance
2. Image by <a href="https://pixabay.com/users/geralt-9301/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1044090">Gerd Altmann</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1044090">Pixabay</a>

# Numpy

In [2]:
import numpy as np

In [4]:
# One Dimensional Array
arr_1d = np.array([1,2,1])
arr_1d

array([1, 2, 1])

In [7]:
arr_2d = np.array([[1,2,1], [2,3,4]])
arr_2d

array([[1, 2, 1],
       [2, 3, 4]])

In [9]:
# Dimensions of the Array
print('Dimensions of the arr_1d: ', np.ndim(arr_1d))
print('Dimensions of the arr_2d: ', np.ndim(arr_2d))

Dimensions of the arr_1d:  1
Dimensions of the arr_2d:  2


In [10]:
# Size of the Array
print("Size of the arr_1d: ", np.size(arr_1d))
print('Size of the arr_2d: ', np.size(arr_2d))

Size of the arr_1d:  3
Size of the arr_2d:  6


In [11]:
# Shape of the Array
print('Shape of the arr_1d: ', np.shape(arr_1d))
print('Shape of the arr_2d: ', np.shape(arr_2d))

Shape of the arr_1d:  (3,)
Shape of the arr_2d:  (2, 3)


In [14]:
# Generating an Array with Sequential Elements
np_range = np.array(range(15))
np_arange = np.array(np.arange(15))
print(np_range)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
# Determining the data type
np_arange.dtype

dtype('int32')

In [17]:
# Recasting Data
np_arange = np.array(np_arange, dtype = 'float64')
np_arange

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [18]:
# Reshaping the Data
np_arange = np.arange(15).reshape(3,5)
np_arange

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
# Transpose Array. Transposes the array by 90 degrees
np_arange.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [22]:
# Original Array remains unchanged
np_arange

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
# Indexing the Array (Second row, second value)
np_arange[1,1]

6

In [26]:
# Change the value inside an array
np_arange[1,1] = 60
np_arange[1,1]

60

In [29]:
# Subsetting the data. Calling the first row only.
np_arange[0]

array([0, 1, 2, 3, 4])

In [30]:
# If we only want the first column
np_arange[:,0]

array([ 0,  5, 10])

In [32]:
# if we want every third element in each row then the code is
np_arange[::,3]

array([ 3,  8, 13])

In [39]:
# Prepolulating the code 
import numpy as np
# Placeholder Arrays
a_zero = np.zeros((5,5))
a_one = np.ones((5,5))
# Sometimes used in liners algebra settings
a_eye = np.eye(5,5, k = 0)
#fills not quite 0 but may be faster than zeros
a_empty = np.empty((25,25))

In [40]:
a_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
a_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
# Create an array of equally spaced values
a = np.linspace(-4,4, 40)
a

array([-4.        , -3.79487179, -3.58974359, -3.38461538, -3.17948718,
       -2.97435897, -2.76923077, -2.56410256, -2.35897436, -2.15384615,
       -1.94871795, -1.74358974, -1.53846154, -1.33333333, -1.12820513,
       -0.92307692, -0.71794872, -0.51282051, -0.30769231, -0.1025641 ,
        0.1025641 ,  0.30769231,  0.51282051,  0.71794872,  0.92307692,
        1.12820513,  1.33333333,  1.53846154,  1.74358974,  1.94871795,
        2.15384615,  2.35897436,  2.56410256,  2.76923077,  2.97435897,
        3.17948718,  3.38461538,  3.58974359,  3.79487179,  4.        ])

In [47]:
a_empty

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [51]:
# Mathmetical Operations
a = np.arange(15).reshape(3,5)
b = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
a**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [53]:
a-b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [54]:
# Set one of the values in the array as 1
a[1,2] = 1
b == a

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [57]:
# Summarizing 
a.sum()

99

In [58]:
a.mean()

6.6

In [59]:
a.max()

14

In [60]:
a.std()

4.572380853195266

In [61]:
#Sum a row
a[0].sum()

10

In [62]:
# Sum a Column
a[:,0].sum()

15

In [63]:
# Numpy Random Module
import numpy.random as npr
npr.standard_normal((3,5))

array([[ 0.13159946,  1.05942962,  0.75102277,  0.09810517, -0.59504901],
       [-0.27002305, -0.05106523,  0.76701851,  1.26536528, -0.86616323],
       [-0.73971338, -0.69642828, -0.33917631, -1.57304964, -1.48892481]])

In [64]:
# Choosing every n-th value 
y = npr.standard_normal(500)
y[:25]

array([ 1.18293353, -0.05128793, -0.26221616, -0.32084335,  0.75041486,
        0.76869642, -0.16226826,  0.19876898,  1.65818   ,  0.26736771,
        0.20558113,  0.26504401, -0.1370339 , -0.89022082, -0.30892212,
       -0.39320667, -0.26278145, -0.13789424,  1.05165312,  0.33757026,
       -1.50431905,  0.27560121, -1.15284215,  0.84043894,  0.46864829])

In [67]:
# Collecting every 12th value from the random data.
y[::12]

array([ 1.18293353, -0.1370339 ,  0.46864829,  1.76956905, -0.55707898,
        0.48056912,  0.28730755, -0.62999171,  1.08379939,  1.11573669,
        1.52808752,  0.9211292 ,  0.26868671,  0.01337536, -0.16411985,
       -0.07559775, -0.50998598, -1.25173282,  0.80165815, -1.01343238,
        0.21307572,  0.6799656 , -0.85550827, -0.26963885,  1.30651127,
        0.42014525, -1.55516072, -1.15025366,  0.36456261, -0.02660852,
        1.17174515,  2.01719499, -0.24177652,  0.63829813,  1.33804965,
       -1.48391492, -1.62239077, -0.275462  ,  0.98578377,  0.23113889,
        1.13032511, -0.92350905])

# Pandas